LojadeJogos/Controllers/CliController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LojadeJogos.Models;
using LojadeJogos.Repositorio;

namespace LojadeJogos.Controllers
{
    public class CliController : Controller
    {

        public ActionResult Cli()
        {
            var cliente = new ModelCi();
            return View(cliente);
        }
        Acoes ac = new Acoes();

        [HttpPost]
        public ActionResult CadCli(ModelCi cliente)
        {
            ac.CadastrarCli(cliente);
            return View(cliente);
        }
    }
}

LojadeJogos/Controllers/FuncController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using LojadeJogos.Models;
using System.Web.Mvc;

namespace LojadeJogos.Controllers
{
    public class FuncController : Controller
    {

        public ActionResult Func()
        {
            var funcio = new ModelFunc();
            return View(funcio);
        }
        Acoes ac = new Acoes();

        [HttpPost]

        public ActionResult CadFunc(ModelFunc func)
        {
            ac.CadastrarFunc(func);
            return View(func);
        }

    }
}

LojadeJogos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Loja de Jogos", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Jogo", "Jogo", "Home")</li>
                    <li>@Html.ActionLink("Cliente", "Cli", "Home")</li>
                    <li>@Html.ActionLink("Funcionário", "Func", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>